// Auto-generated from DuckyScript - DO NOT EDIT MANUALLY
// Generated by duckyscript_compiler.py

#include "attiny85_ducky.h"

ATTinyDuckyKeyboard keyboard(lang_de);

int redLED = LED_BUILTIN;

void setup() {
    pinMode(redLED, OUTPUT);
    digitalWrite(redLED, HIGH);

    // --- PAYLOAD START ---
    // AUTO-GENERATED CODE IS PLACED HERE FROM CONVERTED DUCKYSCRIPT!
    // DON'T EDIT MANUALLY!!!
    // --- PAYLOAD END ---

    digitalWrite(redLED, LOW);
}

void loop() {
    // Empty - payload runs once
}
