// Auto-generated from DuckyScript - DO NOT EDIT MANUALLY
// Generated by duckyscript_compiler.py

#include "attiny85_ducky.h"

ATTinyDuckyKeyboard keyboard(lang_de);

int redLED = LED_BUILTIN;

void setup() {
    pinMode(redLED, OUTPUT);
    digitalWrite(redLED, HIGH);

    // --- PAYLOAD START ---
    keyboard.delay(60000);
    keyboard.sendKeyStroke(KEY_R, KEY_MOD_GUI);
    keyboard.delay(1200);
    keyboard.println(F("https://github.com/3mrgnc3/attiny85_ducky?tab=readme-ov-file#attiny85-ducky"));
    keyboard.sendKeyStroke(KEY_ENTER);
    // --- PAYLOAD END ---

    digitalWrite(redLED, LOW);
}

void loop() {
    // Empty - payload runs once
}
